package memory.objects

import modelClasses.app.user.*
import memory.ids.*
import modelClasses.ids.Media.{BookId, TvEpisodeNumber, MovieId, TvSeasonNumber, TvShowId, VideogameId}

object Users {
  val user1: User = User(
    UserIds.userId1,
    UserProfile(
      "User1",
      "jk78sdfy8dsfhg",
      "user1@gmail.com",
      "Hey there! I'm user 1",
      "Milwaukee, Wisconsin, USA"
    ),
    UserFavourites(
      Some(MovieId(502033)),
      Some(TvShowId(61222)),
      None,
      Some(BookId("7qylv1KYf0kC"))
    ),
    List(
      MovieId(502033),
      BookId("ZEfWEAAAQBAJ"),
      (TvShowId(63247), TvSeasonNumber(1)),
      MovieId(502033)
    ),
    List(),
    List(),
    List(
      BookId("WLmqonsyH0QC"),
    ),
    List(),
    List(
      MediaListIds.mediaListId2,
      MediaListIds.mediaListId3
    ),
    List(
      EntryIds.entryId4,
      EntryIds.entryId10,
      EntryIds.entryId12,
      EntryIds.entryId15
    ),
    List(
      ReviewIds.reviewId4
    ),
    List(
      RatingIds.ratingId4, 
      RatingIds.ratingId10,
      RatingIds.ratingId12
    ),
    List(
      LikeIds.likeId2
    ),
    List(
      ReplyIds.replyId3
    ),
    List(
      UserIds.userId4
    ),
    List(
      UserIds.userId4
    ),
    List(),
    List(
      ChatIds.chatId3
    ),
    List()
  )

  val user2: User = User(
    UserIds.userId2,
    UserProfile(
      "User2",
      "kljhfsdg87ygfjsbhn",
      "user2@gmail.com",
      "Hey there! I'm user 2",
      "London, UK"
    ),
    UserFavourites(
      Some(MovieId(502033)),
      Some(TvShowId(135918)),
      Some(VideogameId(113112)),
      Some(BookId("kHh_EAAAQBAJ"))
    ),
    List(
      MovieId(502033),
      BookId("UU-VAAAACAAJ"),
      VideogameId(284925),
      BookId("WLmqonsyH0QC"),
      MovieId(502033),
      MovieId(502033)
    ),
    List(),
    List(),
    List(),
    List(
      VideogameId(1082),
    ),
    List(
      MediaListIds.mediaListId4
    ),
    List(
      EntryIds.entryId5,
      EntryIds.entryId6,
      EntryIds.entryId9,
      EntryIds.entryId18
      
    ),
    List(
      ReviewIds.reviewId5
    ),
    List(
      RatingIds.ratingId5,
      RatingIds.ratingId6,
      RatingIds.ratingId9,
      RatingIds.ratingId14
    ),
    List(
      LikeIds.likeId1
    ),
    List(
      ReplyIds.replyId2
    ),
    List(
      UserIds.userId4
    ),
    List(
      UserIds.userId4, 
      UserIds.userId5
    ),
    List(),
    List(
      ChatIds.chatId1
    ),
    List(
      ChatIds.chatId6
    )
  )

  val user3: User = User(
    UserIds.userId3,
    UserProfile(
      "User3",
      "89nkj43nhj_9j22az",
      "user3@gmail.com",
      "Hey there! I'm user 3",
      "Milwaukee, Wisconsin, USA"
    ),
    UserFavourites(
      Some(MovieId(94329)),
      Some(TvShowId(77169)),
      Some(VideogameId(144022)),
      None
    ),
    List(
      VideogameId(144022),
      MovieId(837),
      MovieId(502033),
      VideogameId(19564),
    ),
    List(),
    List(),
    List(),
    List(),
    List(
      MediaListIds.mediaListId1
    ),
    List(
      EntryIds.entryId2,
      EntryIds.entryId7
    ),
    List(
      ReviewIds.reviewId2
    ),
    List(
      RatingIds.ratingId2,
      RatingIds.ratingId7
    ),
    List(),
    List(
      ReplyIds.replyId4
    ),
    List(
      UserIds.userId5
    ),
    List(),
    List(),
    List(),
    List()
  )

  val user4: User = User(
    UserIds.userId4,
    UserProfile(
      "User4",
      "78hb7njmdsoil0",
      "user4@gmail.com",
      "Hey there! I'm user 4",
      "London, UK"
    ),
    UserFavourites(
      Some(MovieId(55347)),
      None,
      Some(VideogameId(103298)),
      None
    ),
    List(
      MovieId(55347),
      MovieId(502033)
    ),
    List(),
    List(),
    List(
      VideogameId(113112),
    ),
    List(
      VideogameId(19564),
    ),
    List(
      MediaListIds.mediaListId5,
    ),
    List(
      EntryIds.entryId3,
      EntryIds.entryId11,
      EntryIds.entryId13
    ),
    List(
      ReviewIds.reviewId3
    ),
    List(
      RatingIds.ratingId3,
      RatingIds.ratingId11
    ),
    List(
      LikeIds.likeId4
    ),
    List(
      ReplyIds.replyId1
    ),
    List(
      UserIds.userId1,
      UserIds.userId2
    ),
    List(
      UserIds.userId1,
      UserIds.userId2
    ),
    List(
      UserIds.userId3
    ),
    List(
      ChatIds.chatId4,
      ChatIds.chatId5
    ),
    List()
  )

  val user5: User = User(
    UserIds.userId5,
    UserProfile(
      "User5",
      "129mbnhjiksgad8",
      "user5@gmail.com",
      "Hey there! I'm user 5",
      "Portland, Oregon, USA"
    ),
    UserFavourites(
      None,
      Some(TvShowId(88803)),
      None,
      None
    ),
    List(
      TvShowId(136315),
      TvShowId(100565),
      (TvShowId(136315), TvSeasonNumber(2), TvEpisodeNumber(7)),
      VideogameId(19564),
    ),
    List(),
    List(),
    List(),
    List(),
    List(),
    List(
      EntryIds.entryId1,
      EntryIds.entryId8,
      EntryIds.entryId14,
      EntryIds.entryId16,
    ),
    List(
      ReviewIds.reviewId1,
      ReviewIds.reviewId6
    ),
    List(
      RatingIds.ratingId1,
      RatingIds.ratingId8,
      RatingIds.ratingId13
    ),
    List(
      LikeIds.likeId3
    ),
    List(),
    List(UserIds.userId2),
    List(UserIds.userId3),
    List(),
    List(
      ChatIds.chatId2
    ),
    List()
  )

}